### ISSUE TITLE
If/then nodes

### ISSUE THREAD

**Issue by CharonM72** [joeyballentine/chaiNNer#776] opened 2022-08-20 08:37 UTC
In its simplest form, a numerical test (IF [number] < [number] THEN ...), where the second part could be some number of actions, like deciding where to send a chain (if true, then send to this node; if false, then send to that node).

Something like that would be useful for automation.

**Comment by joeyballentine** [comment] 2022-08-20 08:54
Duplicate of #148 

This is something we plan on doing eventually :)

**Closed by joeyballentine** 2022-08-20 08:54 UTC
