### ISSUE TITLE
This is another one  - Error report for chaiNNer 0.11.1

### ISSUE THREAD

**Issue by skyport** [joeyballentine/chaiNNer#757] opened 2022-08-18 20:58 UTC
Error:
```UnhandledRejection TypeError: Object has been destroyed
    at n.loadURL (node:electron/js2c/browser_init:33:1843)
    at App.mr (/Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:77320)
```
OS: macOS 10.17

**Comment by RunDevelopment** [comment] 2022-08-18 21:06
This seems like a duplicate of #756.

**Comment by joeyballentine** [comment] 2022-08-18 22:16
Yes, this appears to be a duplicate of #756.

**Closed by joeyballentine** 2022-08-18 22:16 UTC

**Comment by joeyballentine** [comment] 2022-08-19 16:36
@skyport, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?

**Comment by skyport** [comment] 2022-08-19 22:59
Now we have another issue: :))

Console Output
Collecting onnx==1.11.0
Downloading onnx-1.11.0.tar.gz (9.9 MB)
9.9/9.9 MB 3.1 MB/s

eta 0:00:00
Preparing metadata (setup.py) : started
Preparing metadata (setup.py): finished with status "error"

Note: This error belongs to ONNX. 
ONNX and NCNN can not be installed.  
It looks like it's downloading but it just stays put. and nothing appears in their console output either.

-----------------------------------------------------------------------------------------------------------------

AND THIS IS THE SYSTEM INFO

{
  "app": {
    "version": "0.11.2",
    "packaged": true,
    "path": "/Applications/chaiNNer.app/Contents/Resources/app"
  },
  "process": {
    "cwd": "/",
    "argv": [
      "/Applications/chaiNNer.app/Contents/MacOS/chainner"
    ]
  },
  "os": {
    "version": "Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101",
    "release": "21.5.0",
    "arch": "x64",
    "endianness": "LE"
  },
  "cpu": {
    "manufacturer": "Apple",
    "brand": "M1",
    "vendor": "Apple",
    "family": "6",
    "model": "",
    "stepping": "0",
    "revision": "",
    "voltage": "",
    "speed": 2.4,
    "speedMin": 2.4,
    "speedMax": 2.4,
    "governor": "",
    "cores": 8,
    "physicalCores": 8,
    "processors": 1,
    "socket": "",
    "flags": "fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe sse3 pclmulqdq dtse64 mon dscpl vmx est tm2 ssse3 cx16 tpr pdcm sse4.1 sse4.2 aes seglim64",
    "virtualization": true,
    "cache": {
      "l1d": 131072,
      "l1i": 65536,
      "l2": 4194304,
      "l3": null
    }
  },
  "gpus": [
    {
      "vendor": "Apple",
      "model": "Apple M1",
      "bus": "Built-In",
      "vramDynamic": true,
      "vram": null,
      "deviceId": "",
      "vendorId": "0x05ac",
      "external": false,
      "cores": "7",
      "metalVersion": "apple7"
    }
  ],
  "settings": {
    "animate-chain": "true",
    "disable-hw-accel": "false",
    "is-cpu": "false",
    "is-fp16": "false",
    "node-favorites": "[]",
    "node-selector-collapsed": "false",
    "snap-to-grid": "false",
    "snap-to-grid-amount": "15",
    "startup-template": "\"\"",
    "use-dark-mode": "true",
    "use-last-directory-chainner:image:load 0": "/Users/itsme/Pictures/Wallpapers",
    "use-last-window-size": "{\"maximized\":true,\"width\":1280,\"height\":720}",
    "use-recently-open": "[]",
    "use-system-python": "false"
  }
}

------------------------------------------------------------------------------------------------------------------

**Comment by joeyballentine** [comment] 2022-08-20 02:24
Ah. M1 would explain it. It seems ncnn and onnx don't currently support m1. At least pytorch should still work.

**Comment by skyport** [comment] 2022-08-20 04:27
Thanks anyway. I was wondering, when will it start supporting? Can you warn me about the subject? Because almost nothing works. So, as it stands, it doesn't seem to work very well. 
All the best

**Comment by joeyballentine** [comment] 2022-08-20 04:41
@skyport Until all these Mac users started coming in, I had no idea any of these issues existed. And I especially didn't know that m1 didn't support ncnn or onnx since I dont have access to an m1 Mac. I'm looking into if I can compile ncnn for arm macos, which would make that work. As for onnx, it does have a runtime for macos specifically so I can see if I can make it install that instead for m1 MacBooks. But I'll need to do some research and probably get some people to test it out for me since I can't. However until then I definitely could add some sort of warning for m1 users

**Comment by skyport** [comment] 2022-08-20 04:50
Your the best. Thanks a lot.
