### ISSUE TITLE
Error report for chaiNNer 0.11.1

### ISSUE THREAD

**Issue by dan04K** [joeyballentine/chaiNNer#760] opened 2022-08-19 00:31 UTC
Error:
```UnhandledRejection Error: Attempted to register a second handler for 'get-port'
    at IpcMainImpl.handle (node:electron/js2c/browser_init:189:337)
    at /private/var/folders/09/bfcwf4w52fs8_qq2d060j_2h0000gq/T/AppTranslocation/6F172B2A-B7BA-4383-A394-C3D7105FC7BD/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71972
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EventEmitter.<anonymous> (/private/var/folders/09/bfcwf4w52fs8_qq2d060j_2h0000gq/T/AppTranslocation/6F172B2A-B7BA-4383-A394-C3D7105FC7BD/d/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:71475)
```
OS: macOS 10.17

**Comment by joeyballentine** [comment] 2022-08-19 00:51
Hello. Thanks for reporting this. This is a known issue.

Since this ticket is a duplicate of #748, I will be closing this one. Feel free to continue discussion about this issue there.

**Closed by joeyballentine** 2022-08-19 00:51 UTC

**Comment by joeyballentine** [comment] 2022-08-19 16:36
@dan04K, could you please try the [latest release](https://github.com/joeyballentine/chaiNNer/releases/tag/v0.11.2) and see if it resolves your issues?
