### ISSUE TITLE
Hover mode for stack images

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#774] opened 2022-08-19 23:44 UTC
**Motivation**
Vertical and horizontal output is not as convenient for comparison as switching through hovering over a block image in node.

**Comment by RunDevelopment** [comment] 2022-08-20 10:08
Sorry, I don't understand what feature you are suggesting. Do you want a comparison view like Cupscale has? Could you please explain it in more detail?

**Comment by 0x4E69676874466F78** [comment] 2022-08-20 10:17
> Do you want a comparison view like Cupscale has? 

Yes. But in Cupscale you need to click on the image, I suggest hover on image (behavior may be customized?).

**Comment by RunDevelopment** [comment] 2022-08-20 10:30
I'm not sure whether we can do something like that easily. The problem is that this requires a custom UI component. It's not like Stack Images that just returns another image.

Doable, yes, but it will probably take a while.

**Comment by 0x4E69676874466F78** [comment] 2022-08-20 10:40
@RunDevelopment yes, possible here is better to create a another node. Thanks!

**Comment by 0x4E69676874466F78** [comment] 2022-08-20 10:58
It is possible if more than two images are submitted at once, to switch pictures through the mouse wheel or add arrow buttons in node.

**Comment by joeyballentine** [comment] 2022-08-20 11:51
> @RunDevelopment yes, possible here is better to create a another node. Thanks!

It is not this simple. What RD it's saying is that it's more complicated than just writing some new processing logic, an entire new UI window needs to be made for that

**Comment by 0x4E69676874466F78** [comment] 2022-08-20 11:58
@joeyballentine 
> It is not this simple. What RD it's saying is that it's more complicated than just writing some new processing logic, an entire new UI window needs to be made for that

in the UI library it is impossible to customize specific nodes? Is everything hardcoded there purely under the existing functionality? if so, that's sad.

**Comment by RunDevelopment** [comment] 2022-08-20 12:17
> in the UI library

The problem isn't that this is impossible, the problem is that we *are* the UI library. So we have to implement this, which isn't easy. With most other suggestions, we can just reuse and remix what we already have, but adding new UI components is more difficult.

**Comment by joeyballentine** [comment] 2022-08-20 13:39
Though if I understand the initial idea correctly, we might be able to just make it a different type of preview component without having to make any of the custom preview window stuff we wanna make. It wouldn't be as good of a feature but it would still work. Imagine the view node with two inputs and when you hover over it, it switches which one it shows

**Comment by joeyballentine** [comment] 2022-08-20 13:40
Of course though since we don't show full resolution previews, it wouldn't be as useful, so for that we might wanna send over a higher resolution image for each

**Comment by theflyingzamboni** [comment] 2022-08-20 20:06
This just sounds like the custom preview window we've already discussed.

**Comment by RunDevelopment** [comment] 2022-08-20 20:40
It does. Did we close that issue already?

**Comment by theflyingzamboni** [comment] 2022-08-21 02:25
No, it's still a planned feature. Unless someone feels this issue has something distinctly different, it should probably be closed as a duplicate of #220.

**Comment by joeyballentine** [comment] 2022-08-21 10:54
Duplicate of #220

**Closed by joeyballentine** 2022-08-21 10:54 UTC
