### ISSUE TITLE
GFPGAN

### ISSUE THREAD

**Issue by sedetweiler** [joeyballentine/chaiNNer#753] opened 2022-08-18 17:50 UTC
Error saying ChaiNNer isn't compatible with this fantastic GAN.  Oh, I also am using your tool on my youtube channel, so you should see a considerable spike in traffic.  Thanks again for making such an amazing tool!

**Comment by RunDevelopment** [comment] 2022-08-18 18:15
Duplicate of #739. 

We are already considering adding it, but it likely won't be easy, so it might take a while until it's available.

> Oh, I also am using your tool on my youtube channel, so you should see a considerable spike in traffic.

Thank you so much for that! Yes, we've seen quite a spike :)

**Comment by joeyballentine** [comment] 2022-08-18 18:44
Definitely bumping up GFPGAN support in priority. Currently working on implementing SwinIR support, but after that I'll work on GFPGAN, and maybe even GPEN as well. 

> Oh, I also am using your tool on my youtube channel, so you should see a considerable spike in traffic. Thanks again for making such an amazing tool!

Definitely seeing a spike in traffic, and a big increase in macos issues unfortunately. Hopefully we can get those handled. Glad you like chaiNNer and thanks for the shout-out! 

I am going to close this issue though as it is a duplicate of #739

**Closed by joeyballentine** 2022-08-18 18:44 UTC

**Comment by sedetweiler** [comment] 2022-08-19 13:50
With the massive influx of AI Art and the fact that all of these sites
create face errors, you are in a great position.  Tencent's site is down,
and that was really the most used front end for that GAN, but was
overwhelmed with people using it to fix the poor faces.  Keep up the great
work!

-sed

**Comment by zelenooki87** [comment] 2022-11-02 15:08
Please modify code to support Gpen models! thank you
